#ifndef GUARD_CONSTANTS_BLUE_STARTER_H
#define GUARD_CONSTANTS_BLUE_STARTER_H

// EventScript_GetBlueStarter results
#define BLUE_STARTER_BULBASAUR  0
#define BLUE_STARTER_CHARMANDER 1
#define BLUE_STARTER_SQUIRTLE   2

#endif // GUARD_CONSTANTS_BLUE_STARTER_H
