#ifndef GUARD_CONSTANTS_MAUVILLE_OLD_MAN_H
#define GUARD_CONSTANTS_MAUVILLE_OLD_MAN_H

#define MAUVILLE_MAN_BARD           0
#define MAUVILLE_MAN_HIPSTER        1
#define MAUVILLE_MAN_STORYTELLER    2
#define MAUVILLE_MAN_GIDDY          3
#define MAUVILLE_MAN_UNUSED1        4
#define MAUVILLE_MAN_UNUSED2        5

#endif // GUARD_CONSTANTS_MAUVILLE_OLD_MAN_H
