#ifndef GUARD_CONSTANTS_SCREEN_EFFECTS_H
#define GUARD_CONSTANTS_SCREEN_EFFECTS_H

#define SCREENFX_INTENSITY_MAX  16

// Shake axis flags (param2).
#define SCREENFX_AXIS_X         (1 << 0)
#define SCREENFX_AXIS_Y         (1 << 1)
#define SCREENFX_SHAKE_MAX_AMPLITUDE    4   // pixels at SCREENFX_INTENSITY_MAX

enum ScreenFxKind
{
    SCREENFX_WAVE,
    SCREENFX_RIPPLE,
    SCREENFX_TEAR,
    SCREENFX_SHAKE,
    SCREENFX_VIGNETTE,
    SCREENFX_KIND_COUNT,
};

enum ScreenFxAnchor
{
    SCREENFX_ANCHOR_NONE,
    SCREENFX_ANCHOR_COORDS,
    SCREENFX_ANCHOR_OBJECT,
};

#endif // GUARD_CONSTANTS_SCREEN_EFFECTS_H
