#ifndef GUARD_CONSTANTS_SCREEN_EFFECTS_H
#define GUARD_CONSTANTS_SCREEN_EFFECTS_H

#define SCREENFX_INTENSITY_MAX  16

enum ScreenFxKind
{
    SCREENFX_WAVE,
    SCREENFX_RIPPLE,
    SCREENFX_TEAR,
    SCREENFX_SHAKE,
    SCREENFX_VIGNETTE,
    SCREENFX_KIND_COUNT,
};

enum ScreenFxAnchor
{
    SCREENFX_ANCHOR_NONE,
    SCREENFX_ANCHOR_COORDS,
    SCREENFX_ANCHOR_OBJECT,
};

#endif // GUARD_CONSTANTS_SCREEN_EFFECTS_H
