#ifndef GUARD_CONSTANTS_VARS_KANTO_H
#define GUARD_CONSTANTS_VARS_KANTO_H

// Kanto vars, stored in SaveBlock2 kantoVars. Ids keep the FireRed order.

// Vars (0x4100-0x4146)
#define VAR_MASSAGE_COOLDOWN_STEP_COUNTER                                      (KANTO_VARS_START + 0x000)
#define VAR_RESORT_GOREGEOUS_STEP_COUNTER                                      (KANTO_VARS_START + 0x001)
#define VAR_RESORT_GORGEOUS_REQUESTED_MON                                      (KANTO_VARS_START + 0x002)
#define VAR_ELEVATOR_FLOOR                                                     (KANTO_VARS_START + 0x003)
#define VAR_RESORT_GORGEOUS_REWARD                                             (KANTO_VARS_START + 0x004)
#define VAR_HERACROSS_SIZE_RECORD                                              (KANTO_VARS_START + 0x005)
#define VAR_MAGIKARP_SIZE_RECORD                                               (KANTO_VARS_START + 0x006)
#define VAR_TRAINER_CARD_MON_ICON_TINT_IDX                                     (KANTO_VARS_START + 0x007)
#define VAR_TRAINER_CARD_MON_ICON_1                                            (KANTO_VARS_START + 0x008)
#define VAR_TRAINER_CARD_MON_ICON_2                                            (KANTO_VARS_START + 0x009)
#define VAR_TRAINER_CARD_MON_ICON_3                                            (KANTO_VARS_START + 0x00A)
#define VAR_TRAINER_CARD_MON_ICON_4                                            (KANTO_VARS_START + 0x00B)
#define VAR_TRAINER_CARD_MON_ICON_5                                            (KANTO_VARS_START + 0x00C)
#define VAR_TRAINER_CARD_MON_ICON_6                                            (KANTO_VARS_START + 0x00D)
#define VAR_HOF_BRAG_STATE                                                     (KANTO_VARS_START + 0x00E)
#define VAR_EGG_BRAG_STATE                                                     (KANTO_VARS_START + 0x00F)
#define VAR_LINK_WIN_BRAG_STATE                                                (KANTO_VARS_START + 0x010)
#define VAR_MAP_SCENE_PALLET_TOWN_OAK                                          (KANTO_VARS_START + 0x011)
#define VAR_MAP_SCENE_VIRIDIAN_CITY_OLD_MAN                                    (KANTO_VARS_START + 0x012)
#define VAR_MAP_SCENE_CERULEAN_CITY_RIVAL                                      (KANTO_VARS_START + 0x013)
#define VAR_VERMILION_CITY_TICKET_CHECK_TRIGGER                                (KANTO_VARS_START + 0x014)
#define VAR_MAP_SCENE_ROUTE22                                                  (KANTO_VARS_START + 0x015)
#define VAR_MAP_SCENE_PALLET_TOWN_PROFESSOR_OAKS_LAB                           (KANTO_VARS_START + 0x016)
#define VAR_MAP_SCENE_PALLET_TOWN_PLAYERS_HOUSE_2F                             (KANTO_VARS_START + 0x017)
#define VAR_MAP_SCENE_VIRIDIAN_CITY_MART                                       (KANTO_VARS_START + 0x018)
#define VAR_MAP_SCENE_PALLET_TOWN_RIVALS_HOUSE                                 (KANTO_VARS_START + 0x019)
#define VAR_MAP_SCENE_POKEMON_TOWER_6F                                         (KANTO_VARS_START + 0x01A)
#define VAR_MAP_SCENE_VIRIDIAN_CITY_GYM_DOOR                                   (KANTO_VARS_START + 0x01B)
#define VAR_MAP_SCENE_S_S_ANNE_2F_CORRIDOR                                     (KANTO_VARS_START + 0x01C)
#define VAR_MAP_SCENE_SILPH_CO_7F                                              (KANTO_VARS_START + 0x01D)
#define VAR_MAP_SCENE_POKEMON_TOWER_2F                                         (KANTO_VARS_START + 0x01E)
#define VAR_MAP_SCENE_ROUTE16                                                  (KANTO_VARS_START + 0x01F)
#define VAR_MAP_SCENE_ROUTE23                                                  (KANTO_VARS_START + 0x020)
#define VAR_MAP_SCENE_SILPH_CO_11F                                             (KANTO_VARS_START + 0x021)
#define VAR_MAP_SCENE_PEWTER_CITY_MUSEUM_1F                                    (KANTO_VARS_START + 0x022)
#define VAR_MAP_SCENE_ROUTE5_ROUTE6_ROUTE7_ROUTE8_GATES                        (KANTO_VARS_START + 0x023)
#define VAR_MAP_SCENE_SEAFOAM_ISLANDS_B4F                                      (KANTO_VARS_START + 0x024)
#define VAR_MAP_SCENE_VICTORY_ROAD_1F                                          (KANTO_VARS_START + 0x025)
#define VAR_MAP_SCENE_VICTORY_ROAD_2F_BOULDER1                                 (KANTO_VARS_START + 0x026)
#define VAR_MAP_SCENE_VICTORY_ROAD_2F_BOULDER2                                 (KANTO_VARS_START + 0x027)
#define VAR_MAP_SCENE_VICTORY_ROAD_3F                                          (KANTO_VARS_START + 0x028)
#define VAR_MAP_SCENE_POKEMON_LEAGUE                                           (KANTO_VARS_START + 0x029)
#define VAR_MAP_SCENE_CINNABAR_ISLAND_POKEMON_LAB_EXPERIMENT_ROOM_WHICH_FOSSIL (KANTO_VARS_START + 0x02A)
#define VAR_MAP_SCENE_CINNABAR_ISLAND_POKEMON_LAB_EXPERIMENT_ROOM_REVIVE_STATE (KANTO_VARS_START + 0x02B)
#define VAR_MAP_SCENE_ROUTE24                                                  (KANTO_VARS_START + 0x02C)
#define VAR_MAP_SCENE_PEWTER_CITY                                              (KANTO_VARS_START + 0x02D)
#define VAR_MAP_SCENE_FUCHSIA_CITY_SAFARI_ZONE_ENTRANCE                        (KANTO_VARS_START + 0x02E)
#define VAR_MAP_SCENE_PALLET_TOWN_SIGN_LADY                                    (KANTO_VARS_START + 0x02F)
#define VAR_MAP_SCENE_CINNABAR_ISLAND                                          (KANTO_VARS_START + 0x030)
#define VAR_MAP_SCENE_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB                    (KANTO_VARS_START + 0x031)
#define VAR_MAP_SCENE_SEVEN_ISLAND_HOUSE_ROOM1                                 (KANTO_VARS_START + 0x032)
#define VAR_MAP_SCENE_ONE_ISLAND_HARBOR                                        (KANTO_VARS_START + 0x033)
#define VAR_MAP_SCENE_ONE_ISLAND_POKEMON_CENTER_1F                             (KANTO_VARS_START + 0x034)
#define VAR_MAP_SCENE_TWO_ISLAND                                               (KANTO_VARS_START + 0x035)
#define VAR_MAP_SCENE_TWO_ISLAND_JOYFUL_GAME_CORNER                            (KANTO_VARS_START + 0x036)
#define VAR_MAP_SCENE_THREE_ISLAND                                             (KANTO_VARS_START + 0x037)
#define VAR_MAP_SCENE_POKEMON_CENTER_TEALA                                     (KANTO_VARS_START + 0x038)
#define VAR_MAP_SCENE_CERULEAN_CITY_ROCKET                                     (KANTO_VARS_START + 0x039)
#define VAR_MAP_SCENE_VERMILION_CITY                                           (KANTO_VARS_START + 0x03A)
#define VAR_MAP_SCENE_MT_EMBER_EXTERIOR                                        (KANTO_VARS_START + 0x03B)
#define VAR_MAP_SCENE_ICEFALL_CAVE_BACK                                        (KANTO_VARS_START + 0x03C)
#define VAR_MAP_SCENE_SAFFRON_CITY_DOJO                                        (KANTO_VARS_START + 0x03D)
#define VAR_MAP_SCENE_TRAINER_TOWER                                            (KANTO_VARS_START + 0x03E)
#define VAR_MAP_SCENE_FIVE_ISLAND_LOST_CAVE_ROOM10                             (KANTO_VARS_START + 0x03F)
#define VAR_MAP_SCENE_FIVE_ISLAND_RESORT_GORGEOUS                              (KANTO_VARS_START + 0x040)
#define VAR_MAP_SCENE_INDIGO_PLATEAU_EXTERIOR                                  (KANTO_VARS_START + 0x041)
#define VAR_MAP_SCENE_FOUR_ISLAND                                              (KANTO_VARS_START + 0x042)
#define VAR_MAP_SCENE_ROCKET_WAREHOUSE                                         (KANTO_VARS_START + 0x043)
#define VAR_MAP_SCENE_SIX_ISLAND_POKEMON_CENTER_1F                             (KANTO_VARS_START + 0x044)
#define VAR_MAP_SCENE_CINNABAR_ISLAND_2                                        (KANTO_VARS_START + 0x045)
#define VAR_MAP_SCENE_MT_MOON_B2F                                              (KANTO_VARS_START + 0x046)

#endif // GUARD_CONSTANTS_VARS_KANTO_H
