FieldChansey_Text_Greeting:
	.string "Chansey: Chaaan-sey!\p"
	.string "It looks ready to help your\n"
	.string "POKéMON rest up.$"

FieldChansey_Text_WhatToDo:
	.string "What would you like to do?$"

FieldChansey_Text_MenuHeal:
	.string "HEAL$"

FieldChansey_Text_MenuPC:
	.string "PC$"

FieldChansey_Text_MenuCancel:
	.string "CANCEL$"

FieldChansey_Text_Healed:
	.string "Your POKéMON have been restored\n"
	.string "to full health.$"
