// Generated by tools/gs_convert/build_world_map2.py. Do not edit.

#define WORLD_MAP_CELLS_W 56
#define WORLD_MAP_CELLS_H 36

// Region ids as stored in sWorldMapRegions; 0 is open sea.
#define WORLD_MAP_REGION_SEA 0
#define WORLD_MAP_REGION_JOHTO 1
#define WORLD_MAP_REGION_KANTO 2
#define WORLD_MAP_REGION_HOENN 3
#define WORLD_MAP_REGION_SEVII 4
#define WORLD_MAP_NUM_REGIONS 4

// Palette banks of the map tiles.
#define WORLD_MAP_BANK_SEA 0
#define WORLD_MAP_BANK_JOHTO 1
#define WORLD_MAP_BANK_KANTO 2
#define WORLD_MAP_BANK_HOENN 3
#define WORLD_MAP_BANK_SEVII123 4
#define WORLD_MAP_BANK_SEVII4567 5
#define WORLD_MAP_BANK_LOCKED 6

// Source panels a cluster is cut from.
#define WORLD_MAP_SRC_JOHTO 0
#define WORLD_MAP_SRC_KANTO 1
#define WORLD_MAP_SRC_HOENN 2
#define WORLD_MAP_SRC_SEVII123 3
#define WORLD_MAP_SRC_SEVII45 4
#define WORLD_MAP_SRC_SEVII67 5

// Cursor start per region (a MAPSEC cell).
static const struct { u8 x; u8 y; } sWorldMapRegionAnchors[WORLD_MAP_NUM_REGIONS + 1] =
{
    [WORLD_MAP_REGION_SEA] = { 0, 0 },
    [WORLD_MAP_REGION_JOHTO] = { 18, 8 },
    [WORLD_MAP_REGION_KANTO] = { 39, 8 },
    [WORLD_MAP_REGION_HOENN] = { 15, 25 },
    [WORLD_MAP_REGION_SEVII] = { 43, 24 },
};

// Source rect inside the panel-local 28x15 grid, and the offset to world cells.
static const struct WorldMapCluster sWorldMapClusters[] =
{
    { WORLD_MAP_SRC_JOHTO, 1, 0, 24, 14, 6, 2 },
    { WORLD_MAP_SRC_KANTO, 2, 1, 17, 14, 29, 2 },
    { WORLD_MAP_SRC_HOENN, 0, 0, 28, 15, 2, 19 },
    { WORLD_MAP_SRC_SEVII123, 1, 3, 2, 8, 31, 16 },
    { WORLD_MAP_SRC_SEVII123, 9, 7, 1, 3, 27, 13 },
    { WORLD_MAP_SRC_SEVII123, 14, 12, 6, 2, 22, 12 },
    { WORLD_MAP_SRC_SEVII45, 3, 4, 1, 1, 41, 16 },
    { WORLD_MAP_SRC_SEVII45, 10, 8, 1, 1, 31, 23 },
    { WORLD_MAP_SRC_SEVII45, 14, 9, 5, 6, 29, 14 },
    { WORLD_MAP_SRC_SEVII67, 15, 0, 4, 9, 35, 19 },
    { WORLD_MAP_SRC_SEVII67, 3, 6, 7, 7, 29, 21 },
    { WORLD_MAP_SRC_SEVII67, 18, 13, 1, 1, 34, 18 },
};
