#!/usr/bin/env python3
"""Build the Johto region grid (GS Stage 28.3).

Reads the HnS Johto 28x15 MAPSEC grid, remaps HnS MAPSEC names to the target constants (Stage 3
fold table), and writes:
  src/data/region_map/region_map_layout_johto.h   sRegionMapSections_Johto[15][28]
and fills panel-local x/y/width/height for the Johto MAPSECs in region_map_sections.json.

The combined world grid is generated by build_world_map2.py (GS Stage 28.10).

Usage: build_world_layout.py [--hns PATH]
"""

import argparse
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import ROOT, add_hns_arg  # noqa: E402
from apply_classification import MAPSEC_FOLDS, MAPSEC_CUT  # noqa: E402

DATA = os.path.join(ROOT, "src/data/region_map")
GRID_W, GRID_H = 28, 15


def parse_grid(path):
    rows = []
    for line in open(path):
        line = line.strip()
        if line.startswith("{") and "MAPSEC_" in line:
            rows.append(re.findall(r"MAPSEC_\w+", line))
    assert len(rows) == GRID_H and all(len(r) == GRID_W for r in rows), path
    return rows


def remap(tok):
    if tok in MAPSEC_CUT:
        return "MAPSEC_NONE"
    return MAPSEC_FOLDS.get(tok, tok)


def write_grid(path, name, grid, header):
    with open(path, "w") as f:
        f.write(header)
        f.write("static const u8 %s[MAP_HEIGHT][MAP_WIDTH] = {\n" % name)
        for row in grid:
            f.write("    {%s},\n" % ", ".join(row))
        f.write("};\n")


def main():
    ap = argparse.ArgumentParser()
    add_hns_arg(ap)
    args = ap.parse_args()

    hns_grid = parse_grid(os.path.join(args.hns, "src/data/region_map/region_map_layout_johto.h"))
    johto = [[remap(t) for t in row] for row in hns_grid]
    header = "// Generated by tools/gs_convert/build_world_layout.py. Do not edit.\n\n"
    write_grid(os.path.join(DATA, "region_map_layout_johto.h"), "sRegionMapSections_Johto", johto, header)

    # Panel-local Johto bounding boxes (folded cells share one MAPSEC).
    boxes = {}
    for y, row in enumerate(johto):
        for x, tok in enumerate(row):
            if tok != "MAPSEC_NONE":
                b = boxes.setdefault(tok, [x, y, x, y])
                b[0], b[1] = min(b[0], x), min(b[1], y)
                b[2], b[3] = max(b[2], x), max(b[3], y)

    jpath = os.path.join(DATA, "region_map_sections.json")
    data = json.load(open(jpath))
    consts = open(os.path.join(ROOT, "include/constants/region_map_sections.h")).read()
    start = consts.index("MAPSEC_NEW_BARK_TOWN,")
    end = consts.index("MAPSEC_JOHTO_LEAGUE,")
    johto_ids = re.findall(r"MAPSEC_\w+", consts[start:end + len("MAPSEC_JOHTO_LEAGUE")])
    unplaced = []
    for sec in data["map_sections"]:
        if sec["id"] not in johto_ids:
            continue
        b = boxes.get(sec["id"])
        if not b:
            unplaced.append(sec["id"])
            continue
        # Key order matches the Hoenn entries: id, name, x, y, width, height.
        sec.update(x=b[0], y=b[1], width=b[2] - b[0] + 1, height=b[3] - b[1] + 1)
    with open(jpath, "w") as f:
        f.write(json.dumps(data, indent=2, ensure_ascii=False) + "\n")

    print("Johto MAPSECs placed: %d / %d" % (len(boxes), len(johto_ids)))
    print("Unplaced (no grid cell): %s" % ", ".join(unplaced))
    unknown = sorted({t for r in johto for t in r if t not in johto_ids and t != "MAPSEC_NONE"})
    print("Johto grid tokens outside Johto MAPSEC range: %s" % ", ".join(unknown))


if __name__ == "__main__":
    main()
