#!/usr/bin/env python3
"""Build the Johto region grid and the combined world MAPSEC grid (GS Stage 28.3).

Reads the HnS Johto 28x15 MAPSEC grid, remaps HnS MAPSEC names to the target constants (Stage 3
fold table), and writes:
  src/data/region_map/region_map_layout_johto.h   sRegionMapSections_Johto[15][28]
  src/data/region_map/region_map_layout_world.h   sWorldMapSections[45][56]
and fills panel-local x/y/width/height for the Johto MAPSECs in region_map_sections.json.

The world grid places each panel's layout at its origin from world_map_layout.h (generated by
build_world_map.py). Run build_world_map.py first.

Usage: build_world_layout.py [--hns PATH] [--print]
"""

import argparse
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import ROOT, add_hns_arg  # noqa: E402
from apply_classification import MAPSEC_FOLDS, MAPSEC_CUT  # noqa: E402

DATA = os.path.join(ROOT, "src/data/region_map")
GRID_W, GRID_H = 28, 15
WORLD_W, WORLD_H = 56, 45

# panel -> (layout header, array name); Johto is generated here.
SOURCES = {
    "HOENN": ("region_map_layout.h", "sRegionMap_MapSectionLayout"),
    "KANTO": ("region_map_layout_kanto.h", "sRegionMapSections_Kanto"),
    "SEVII123": ("region_map_layout_sevii123.h", "sRegionMapSections_Sevii123"),
    "SEVII45": ("region_map_layout_sevii45.h", "sRegionMapSections_Sevii45"),
    "SEVII67": ("region_map_layout_sevii67.h", "sRegionMapSections_Sevii67"),
}
PANEL_ORDER = ["JOHTO", "KANTO", "HOENN", "SEVII123", "SEVII45", "SEVII67"]


def parse_grid(path):
    rows = []
    for line in open(path):
        line = line.strip()
        if line.startswith("{") and "MAPSEC_" in line:
            rows.append(re.findall(r"MAPSEC_\w+", line))
    assert len(rows) == GRID_H and all(len(r) == GRID_W for r in rows), path
    return rows


def remap(tok):
    if tok in MAPSEC_CUT:
        return "MAPSEC_NONE"
    return MAPSEC_FOLDS.get(tok, tok)


def write_grid(path, name, grid, header):
    with open(path, "w") as f:
        f.write(header)
        f.write("static const u8 %s[MAP_HEIGHT][MAP_WIDTH] = {\n" % name)
        for row in grid:
            f.write("    {%s},\n" % ", ".join(row))
        f.write("};\n")


def main():
    ap = argparse.ArgumentParser()
    add_hns_arg(ap)
    ap.add_argument("--print", action="store_true", help="print the world grid")
    args = ap.parse_args()

    layout = open(os.path.join(DATA, "world_map_layout.h")).read()
    panel = {}
    for p in PANEL_ORDER:
        panel[p] = {k: int(re.search(r"WORLD_MAP_%s_%s (\d+)" % (p, k), layout).group(1))
                    for k in ("X", "Y", "W", "H", "SRC_X", "SRC_Y")}

    hns_grid = parse_grid(os.path.join(args.hns, "src/data/region_map/region_map_layout_johto.h"))
    johto = [[remap(t) for t in row] for row in hns_grid]
    header = "// Generated by tools/gs_convert/build_world_layout.py. Do not edit.\n\n"
    write_grid(os.path.join(DATA, "region_map_layout_johto.h"), "sRegionMapSections_Johto", johto, header)

    grids = {"JOHTO": johto}
    for p, (fn, _) in SOURCES.items():
        grids[p] = parse_grid(os.path.join(DATA, fn))

    world = [["MAPSEC_NONE"] * WORLD_W for _ in range(WORLD_H)]
    for p in PANEL_ORDER:
        g, o = grids[p], panel[p]
        for y in range(o["H"]):
            for x in range(o["W"]):
                tok = g[o["SRC_Y"] + y][o["SRC_X"] + x]
                world[o["Y"] + y][o["X"] + x] = tok
        # Cells outside the crop must be empty or the world grid loses them.
        for y in range(GRID_H):
            for x in range(GRID_W):
                inside = o["SRC_X"] <= x < o["SRC_X"] + o["W"] and o["SRC_Y"] <= y < o["SRC_Y"] + o["H"]
                if not inside and g[y][x] != "MAPSEC_NONE":
                    print("warning: %s cell (%d,%d) %s outside crop" % (p, x, y, g[y][x]))

    header = ("// Generated by tools/gs_convert/build_world_layout.py. Do not edit.\n\n"
              "#define WORLD_MAP_CELLS_W %d\n#define WORLD_MAP_CELLS_H %d\n\n" % (WORLD_W, WORLD_H))
    path = os.path.join(DATA, "region_map_layout_world.h")
    with open(path, "w") as f:
        f.write(header)
        f.write("static const u8 sWorldMapSections[WORLD_MAP_CELLS_H][WORLD_MAP_CELLS_W] = {\n")
        for row in world:
            f.write("    {%s},\n" % ", ".join(row))
        f.write("};\n")

    # Panel-local Johto bounding boxes (folded cells share one MAPSEC).
    boxes = {}
    for y, row in enumerate(johto):
        for x, tok in enumerate(row):
            if tok != "MAPSEC_NONE":
                b = boxes.setdefault(tok, [x, y, x, y])
                b[0], b[1] = min(b[0], x), min(b[1], y)
                b[2], b[3] = max(b[2], x), max(b[3], y)

    jpath = os.path.join(DATA, "region_map_sections.json")
    data = json.load(open(jpath))
    consts = open(os.path.join(ROOT, "include/constants/region_map_sections.h")).read()
    start = consts.index("MAPSEC_NEW_BARK_TOWN,")
    end = consts.index("MAPSEC_JOHTO_LEAGUE,")
    johto_ids = re.findall(r"MAPSEC_\w+", consts[start:end + len("MAPSEC_JOHTO_LEAGUE")])
    unplaced = []
    for sec in data["map_sections"]:
        if sec["id"] not in johto_ids:
            continue
        b = boxes.get(sec["id"])
        if not b:
            unplaced.append(sec["id"])
            continue
        # Key order matches the Hoenn entries: id, name, x, y, width, height.
        sec.update(x=b[0], y=b[1], width=b[2] - b[0] + 1, height=b[3] - b[1] + 1)
    with open(jpath, "w") as f:
        f.write(json.dumps(data, indent=2, ensure_ascii=False) + "\n")

    print("Johto MAPSECs placed: %d / %d" % (len(boxes), len(johto_ids)))
    print("Unplaced (no grid cell): %s" % ", ".join(unplaced))
    unknown = sorted({t for r in johto for t in r if t not in johto_ids and t != "MAPSEC_NONE"})
    print("Johto grid tokens outside Johto MAPSEC range: %s" % ", ".join(unknown))
    if args.print:
        ids = {}
        for r in world:
            for t in r:
                ids.setdefault(t, chr(ord("A") + len(ids) % 26) if t != "MAPSEC_NONE" else ".")
        for r in world:
            print("".join("." if t == "MAPSEC_NONE" else ids[t] for t in r))


if __name__ == "__main__":
    main()
