#ifndef GUARD_tilesets_H
#define GUARD_tilesets_H

extern const u32 gTilesetTiles_General[];
extern const u16 gTilesetPalettes_General[][16];

extern const struct Tileset *const gTilesetPointer_SecretBase;
extern const struct Tileset *const gTilesetPointer_SecretBaseRedCave;

extern const struct Tileset gTileset_Building;
extern const struct Tileset gTileset_BuildingKanto;
extern const struct Tileset gTileset_BrendansMaysHouse;
extern const struct Tileset gTileset_GenericBuilding1;
extern const struct Tileset gTileset_General;
extern const struct Tileset gTileset_Petalburg;
extern const struct Tileset gTileset_Rustboro;
extern const struct Tileset gTileset_Fallarbor;
extern const struct Tileset gTileset_Mauville;
extern const struct Tileset gTileset_Slateport;
extern const struct Tileset gTileset_Dewford;
extern const struct Tileset gTileset_Lilycove;
extern const struct Tileset gTileset_Mossdeep;
extern const struct Tileset gTileset_Sootopolis;
extern const struct Tileset gTileset_EverGrande;
extern const struct Tileset gTileset_Pacifidlog;
extern const struct Tileset gTileset_PetalburgGym;
extern const struct Tileset gTileset_PokemonCenter;
extern const struct Tileset gTileset_InsideShip;
extern const struct Tileset gTileset_Fallarbor;
extern const struct Tileset gTileset_Shop;
extern const struct Tileset gTileset_Dewford;
extern const struct Tileset gTileset_BattleFrontier;
extern const struct Tileset gTileset_BattleFrontierOutsideWest;
extern const struct Tileset gTileset_BattleFrontierOutsideEast;
extern const struct Tileset gTileset_BattleArena;
extern const struct Tileset gTileset_BattleDome;
extern const struct Tileset gTileset_BattlePalace;
extern const struct Tileset gTileset_Slateport;
extern const struct Tileset gTileset_Mauville;
extern const struct Tileset gTileset_BattleFrontierOutsideWest;
extern const struct Tileset gTileset_BattleTent;
extern const struct Tileset gTileset_TrainerHill;
extern const struct Tileset gTileset_GeneralKanto;
extern const struct Tileset gTileset_PalletTown;
extern const struct Tileset gTileset_ViridianCity;
extern const struct Tileset gTileset_PewterCity;
extern const struct Tileset gTileset_SaffronCity;
extern const struct Tileset gTileset_CeruleanCity;
extern const struct Tileset gTileset_LavenderTown;
extern const struct Tileset gTileset_VermilionCity;
extern const struct Tileset gTileset_CeladonCity;
extern const struct Tileset gTileset_FuchsiaCity;
extern const struct Tileset gTileset_CinnabarIsland;
extern const struct Tileset gTileset_SeviiIslands123;
extern const struct Tileset gTileset_SeviiIslands45;
extern const struct Tileset gTileset_SeviiIslands67;
extern const struct Tileset gTileset_DepartmentStore;
extern const struct Tileset gTileset_PokemonCenterFrlg;
extern const struct Tileset gTileset_SilphCo;
extern const struct Tileset gTileset_SSAnne;
extern const struct Tileset gTileset_SeaCottage;
extern const struct Tileset gTileset_TrainerTower;


// Johto tilesets (GS Stage 8)
extern const struct Tileset gTileset_AzaleaTown_Gym_Johto;
extern const struct Tileset gTileset_AzaleaTown_Johto;
extern const struct Tileset gTileset_Barn_Johto;
extern const struct Tileset gTileset_BellchimeTrail_Johto;
extern const struct Tileset gTileset_BikeShop_Johto;
extern const struct Tileset gTileset_BlackthornGym_Johto;
extern const struct Tileset gTileset_Blackthorn_General_Johto;
extern const struct Tileset gTileset_Blackthorn_Johto;
extern const struct Tileset gTileset_BurnedTower_Johto;
extern const struct Tileset gTileset_Cafe_Johto;
extern const struct Tileset gTileset_Cave_Default_Johto;
extern const struct Tileset gTileset_Cave_DragonsDen_Johto;
extern const struct Tileset gTileset_Cave_DragonsDen_NorthEast_Johto;
extern const struct Tileset gTileset_Cave_Gray_General_Johto;
extern const struct Tileset gTileset_Cave_Gray_Johto;
extern const struct Tileset gTileset_Cave_Ice_Johto;
extern const struct Tileset gTileset_CherrygroveCity_Johto;
extern const struct Tileset gTileset_CherrygroveCity_NorthEast_Johto;
extern const struct Tileset gTileset_CianwoodCity_Gym_Johto;
extern const struct Tileset gTileset_CianwoodCity_Johto;
extern const struct Tileset gTileset_DepartmentStore_Johto;
extern const struct Tileset gTileset_DragonsDen_Shrine_Johto;
extern const struct Tileset gTileset_EcruteakCity_Gym_Johto;
extern const struct Tileset gTileset_EcruteakTheater_Johto;
extern const struct Tileset gTileset_Ecruteak_City_General_Johto;
extern const struct Tileset gTileset_Ecruteak_City_Johto;
extern const struct Tileset gTileset_GameCorner_Johto;
extern const struct Tileset gTileset_Gate_Standard_Johto;
extern const struct Tileset gTileset_GoldenrodCity_TrainStation_Johto;
extern const struct Tileset gTileset_GoldenrodUndergroundRocket_Johto;
extern const struct Tileset gTileset_GoldenrodUndergroundTunnel_Johto;
extern const struct Tileset gTileset_Goldenrod_Johto;
extern const struct Tileset gTileset_Goldenrod_Underground_Storage_Johto;
extern const struct Tileset gTileset_HallOfFame_Johto;
extern const struct Tileset gTileset_House_2_Johto;
extern const struct Tileset gTileset_House_Lab_Johto;
extern const struct Tileset gTileset_IlexForest_Johto;
extern const struct Tileset gTileset_IndigoPlateau_Johto;
extern const struct Tileset gTileset_JohtoBikeShop_Johto;
extern const struct Tileset gTileset_JohtoBuilding;
extern const struct Tileset gTileset_JohtoGeneral;
extern const struct Tileset gTileset_JohtoKantoGeneral;
extern const struct Tileset gTileset_JohtoMart_Johto;
extern const struct Tileset gTileset_JohtoNorthEast;
extern const struct Tileset gTileset_JohtoNorthWest;
extern const struct Tileset gTileset_JohtoSouth;
extern const struct Tileset gTileset_Kanto_PokemonCenter_Johto;
extern const struct Tileset gTileset_KurtsHouse_Johto;
extern const struct Tileset gTileset_Lighthouse_Johto;
extern const struct Tileset gTileset_MahoganyTown_Johto;
extern const struct Tileset gTileset_MtSilverSnow_Johto;
extern const struct Tileset gTileset_NationalPark_Johto;
extern const struct Tileset gTileset_NewBarkTown_Johto;
extern const struct Tileset gTileset_OlivineCity_Johto;
extern const struct Tileset gTileset_PlayersHouse_Johto;
extern const struct Tileset gTileset_PokemonCenter_White_Johto;
extern const struct Tileset gTileset_PokemonDayCare_Johto;
extern const struct Tileset gTileset_PokemonLeague_Johto;
extern const struct Tileset gTileset_PortIndoor_Johto;
extern const struct Tileset gTileset_PowerPlant_GeneratorRoom_Johto;
extern const struct Tileset gTileset_Route32_Johto;
extern const struct Tileset gTileset_Route38_Farmland_Johto;
extern const struct Tileset gTileset_Route40_Johto;
extern const struct Tileset gTileset_RuinsOfAlphWriting_Johto;
extern const struct Tileset gTileset_RuinsOfAlph_B1F_Johto;
extern const struct Tileset gTileset_RuinsOfAlph_Outside_Johto;
extern const struct Tileset gTileset_SafariZoneJohto_General_Johto;
extern const struct Tileset gTileset_SafariZoneJohto_Johto;
extern const struct Tileset gTileset_SafariZone_Entrance_Johto;
extern const struct Tileset gTileset_ShopRooftop_Johto;
extern const struct Tileset gTileset_SootopolisGym_Johto;
extern const struct Tileset gTileset_TrainerSchool_Johto;
extern const struct Tileset gTileset_VioletCity_Johto;
extern const struct Tileset gTileset_ViridianCity_Johto;
extern const struct Tileset gTileset_ViridianCity_NorthEast_Johto;
extern const struct Tileset gTileset_WhirlIslands_Johto;

#endif //GUARD_tilesets_H
