#!/usr/bin/env python3
"""Author species for the Kanto-north wild tables (Stage 26).

Covers Route 12-18, Route 19-21, Route 23, Victory Road, Pokemon Tower, Pokemon Mansion, Power
Plant, Seafoam Islands, Safari Zone, Cerulean Cave and the Celadon / Fuchsia / Cinnabar waters.
Levels, encounter rates and slot counts are kept; only species change. Sevii Islands are Stage 27.

Rules, helpers and layout are shared with author_wild_south.py (Stage 25): type / theme variety per
area, all nine generations, no Ultra Beast / Paradox / legendary / sub-legendary / mythical / totem.
Land: 6 species per time (common first), spread over 12 slots by LAND_PATTERN. Water, rock smash and
fishing: one list per field, identical for all four times.

Run from the repository root:  python3 tools/frlg_convert/author_wild_north.py [--dry-run]
"""
import argparse
import json
from collections import OrderedDict

from author_wild_south import (JSON_PATH, LAND_PATTERN, LAND_WEIGHTS, MIN_GEN_SHARE, MIN_GENS,
                               MIN_MAP_GENS, TIMES, gen_of, load_banned, load_species, parse, set_species)

# map -> four land lists (Morning, Day, Evening, Night), each 6 species, common first.
LAND = {
    "ROUTE12": (
        "SKWOVET FOMANTIS BELLSPROUT TROPIUS SNORLAX COTTONEE",
        "MUDBRAY MAREEP LOMBRE SEEDOT BIBAREL TROPIUS",
        "MAREANIE SMOLIV ODDISH PACHIRISU BUNEARY SLOWPOKE",
        "NICKIT GLOOM HOOTHOOT MORELULL VENONAT DROWZEE",
    ),
    "ROUTE13": (
        "WINGULL DEERLING FLETCHINDER LECHONK BUNEARY PIDGEY",
        "BLITZLE TOGEDEMARU WOOLOO CUFANT SKIDDO DODUO",
        "PACHIRISU TOGEDEMARU YAMASK HOUNDOUR SHINX SKIDDO",
        "VULLABY ZORUA IMPIDIMP POOCHYENA NATU KOFFING",
    ),
    "ROUTE14": (
        "FLETCHLING PIDOVE ROOKIDEE SQUAWKABILLY TAILLOW FARFETCHD",
        "GIRAFARIG SHROOMISH PAWMI WOOLOO LECHONK GOLBAT",
        "SKIDDO PACHIRISU FOMANTIS WOOLOO NATU TAUROS",
        "MURKROW STUNKY GREAVARD CROAGUNK KOFFING ZUBAT",
    ),
    "ROUTE15": (
        "STARLY PETILIL HOPPIP SENTRET MANKEY FOMANTIS",
        "SMOLIV MAREEP CUBCHOO CHATOT SPEAROW FARFETCHD",
        "ESPURR GOTHITA PACHIRISU CRABRAWLER BLIPBUG DUCKLETT",
        "SKORUPI MURKROW ROCKRUFF HOOTHOOT HOUNDOUR NICKIT",
    ),
    "ROUTE16": (
        "PIDOVE FLETCHINDER CRABRAWLER WATTREL DODUO RATTATA",
        "ROOKIDEE PAWMI PANCHAM SLUGMA YUNGOOS SPEAROW",
        "SKIDDO TOGEDEMARU YAMPER LILLIPUP RATICATE PIDGEOTTO",
        "NOCTOWL SABLEYE CORVISQUIRE MURKROW HOUNDOUR GASTLY",
    ),
    "ROUTE17": (
        "BRAVIARY TAILLOW ROOKIDEE SPEAROW PIKIPEK DODUO",
        "KLAWF SKWOVET PHANPY SCRAGGY RHYHORN CUBONE",
        "FIDOUGH SHINX ROCKRUFF DEERLING PONYTA SANDSHREW",
        "SALANDIT MASCHIFF MIGHTYENA STUNKY HOUNDOUR GROWLITHE",
    ),
    "ROUTE18": (
        "WINGULL FLETCHLING ROOKIDEE SQUAWKABILLY FARFETCHD PIDGEOTTO",
        "ZIGZAGOON PIDOVE GUMSHOOS SKWOVET HOPPIP FEAROW",
        "STARAVIA BLITZLE LILLIPUP SENTRET RATTATA CHANSEY",
        "NOCTOWL VULLABY MURKROW SPINARAK POOCHYENA ZUBAT",
    ),
    "ROUTE21_NORTH": (
        "WINGULL BOUNSWEET LECHONK TAUROS BELLOSSOM PIDGEY",
        "CHATOT DEERLING SKIDDO MAREANIE LILLIPUP BELLSPROUT",
        "GOSSIFLEUR MAREEP PACHIRISU SMOLIV BUNEARY SLOWPOKE",
        "MORELULL NATU HOOTHOOT SKORUPI GASTLY HOUNDOUR",
    ),
    "ROUTE21_SOUTH": (
        "WINGULL SKWOVET FLETCHLING PAWMI TANGELA TAUROS",
        "BLITZLE SMOLIV MAREEP DODUO STARAVIA BUNEARY",
        "DEDENNE YAMPER CHERUBI SENTRET PACHIRISU MEOWTH",
        "ESPURR VULLABY GREAVARD IMPIDIMP SPINARAK KOFFING",
    ),
    "ROUTE23": (
        "NACLI FEAROW HERDIER SKIDDO RHYHORN GEODUDE",
        "SILICOBRA TIMBURR SANDSLASH MAKUHITA PHANPY GOLBAT",
        "ORTHWORM RIOLU ROCKRUFF CUFANT STEELIX FEAROW",
        "SALANDIT GREAVARD MAWILE SABLEYE PAWNIARD GRAVELER",
    ),
    "VICTORY_ROAD_1F_FRLG": (
        "ROLYCOLY GEODUDE NACLI CRANIDOS GRAVELER MACHOKE",
        "NACLI HAWLUCHA TIMBURR DRILBUR ZUBAT MAKUHITA",
        "SHIELDON SCRAGGY ORTHWORM MAWILE BRONZOR GRAVELER",
        "SABLEYE GREAVARD PAWNIARD SPIRITOMB ZUBAT MACHOP",
    ),
    "VICTORY_ROAD_2F": (
        "CARBINK ROGGENROLA SANDYGAST NACLI GOLBAT GRAVELER",
        "BONSLY CRABRAWLER LUCARIO ONIX HAWLUCHA TIMBURR",
        "NOSEPASS TORKOAL FERROSEED SKARMORY ARON BRONZOR",
        "MAWILE DURANT ZUBAT SPIRITOMB DEINO SABLEYE",
    ),
    "VICTORY_ROAD_3F": (
        "ARON GURDURR KLAWF CARKOL DWEBBLE ONIX",
        "ROCKRUFF KLAWF HAWLUCHA CRANIDOS TYRUNT MACHOKE",
        "TOGEDEMARU SKARMORY KLANG BELDUM GRAVELER GOLBAT",
        "GREAVARD LAMPENT BISHARP PAWNIARD GOLBAT HELIOLISK",
    ),
    "POKEMON_TOWER_3F": (
        "PHANTUMP SHUPPET DUSKULL GASTLY ZUBAT MISDREAVUS",
        "LITWICK SINISTEA YAMASK DRIFLOON GASTLY HAUNTER",
        "PUMPKABOO HONEDGE ROLYCOLY SHUPPET GASTLY ZUBAT",
        "GREAVARD FRILLISH PHANTUMP CURSOLA MISMAGIUS GASTLY",
    ),
    "POKEMON_TOWER_4F": (
        "DUSKULL SHUPPET DRIFLOON YAMASK GASTLY HAUNTER",
        "LITWICK PHANTUMP SINISTEA MISDREAVUS ZUBAT GASTLY",
        "MIMIKYU GOLETT SHUPPET HONEDGE GASTLY HAUNTER",
        "GREAVARD DUSCLOPS BRONZOR PUMPKABOO GASTLY ZUBAT",
    ),
    "POKEMON_TOWER_5F": (
        "SHUPPET DUSKULL LITWICK DRIFLOON GASTLY HAUNTER",
        "PHANTUMP YAMASK SINISTEA MISDREAVUS ZUBAT GASTLY",
        "GOLETT FLITTLE HONEDGE ROLYCOLY GASTLY HAUNTER",
        "GREAVARD SPIRITOMB SHUPPET PUMPKABOO GASTLY ZUBAT",
    ),
    "POKEMON_TOWER_6F": (
        "DUSKULL SHUPPET GASTLY HAUNTER PUMPKABOO LITWICK",
        "PHANTUMP SINISTEA DRIFLOON MISDREAVUS HAUNTER GASTLY",
        "YAMASK LITWICK HONEDGE SINISTEA GASTLY HAUNTER",
        "GREAVARD FRILLISH SHUPPET DUSCLOPS GASTLY ZUBAT",
    ),
    "POKEMON_TOWER_7F": (
        "DUSKULL SHUPPET GASTLY HAUNTER GREAVARD LITWICK",
        "PHANTUMP SINISTEA DRIFLOON MISDREAVUS HAUNTER GASTLY",
        "YAMASK LITWICK HONEDGE DUSCLOPS GASTLY HAUNTER",
        "GREAVARD CURSOLA PUMPKABOO MISMAGIUS GASTLY GOLBAT",
    ),
    "POKEMON_MANSION_1F": (
        "SALANDIT CHARCADET GRIMER SLUGMA KOFFING MAGMAR",
        "SLUGMA SALANDIT SIZZLIPEDE TORKOAL MAGNEMITE VULPIX",
        "CAPSAKID VOLTORB TORKOAL HELIOPTILE KLINK GRIMER",
        "CHARCADET LITWICK MURKROW KOFFING GROWLITHE ZUBAT",
    ),
    "POKEMON_MANSION_2F": (
        "SALANDIT LITLEO GRIMER SLUGMA CHARMANDER FLAREON",
        "SLUGMA NUMEL ROLYCOLY HOUNDOUR SKWOVET VULPIX",
        "TOGEDEMARU TADBULB TORKOAL VOLTORB KLINK MAGNEMITE",
        "LITWICK CHARCADET MURKROW KOFFING GROWLITHE ZUBAT",
    ),
    "POKEMON_MANSION_3F": (
        "SALANDIT SIZZLIPEDE GRIMER TORKOAL VULPIX CAPSAKID",
        "SLUGMA SALANDIT CAPSAKID HOUNDOUR FLAREON MAGNEMITE",
        "TADBULB TORKOAL KLINK HELIOPTILE VOLTORB SCRAGGY",
        "LITWICK CHARCADET MURKROW GROWLITHE ZUBAT MUK",
    ),
    "POKEMON_MANSION_B1F": (
        "SALANDIT CHARCADET SLUGMA HEATMOR GRIMER PONYTA",
        "SLUGMA TORKOAL BRONZOR HOUNDOUR GROWLITHE MAGNEMITE",
        "TOXEL SKORUPI KLINK MAGMAR VOLTORB TOGEDEMARU",
        "LITWICK CHARCADET MURKROW KOFFING ZUBAT MUK",
    ),
    "POWER_PLANT": (
        "PACHIRISU TOGEDEMARU VOLTORB TADBULB MAGNEMITE ELECTABUZZ",
        "ELEKID TADBULB PINCURCHIN SHINX HELIOPTILE MAGNETON",
        "ELECTRIKE TYNAMO KLINK DEDENNE JOLTIK ROTOM",
        "TOXEL BLITZLE MAREEP VOLTORB ELECTABUZZ MAGNEMITE",
    ),
    "SAFARI_ZONE_CENTER": (
        "LECHONK BIDOOF SKIDDO KANGASKHAN PINSIR CHANSEY",
        "HOPPIP SKWOVET BOUNSWEET EXEGGCUTE TAUROS MAREEP",
        "PHANPY PAWMI LILLIPUP HERACROSS PANCHAM BELLSPROUT",
        "HATENNA STANTLER WYNAUT TROPIUS NIDORAN_M VENONAT",
    ),
    "SAFARI_ZONE_EAST": (
        "ROOKIDEE SENTRET YUNGOOS KANGASKHAN PINSIR SCYTHER",
        "BIDOOF SKIDDO LECHONK EXEGGCUTE GIRAFARIG CHANSEY",
        "FIDOUGH PHANPY PANCHAM MANKEY HERACROSS ABRA",
        "DEERLING STUNKY STANTLER HATENNA NIDORAN_M VENONAT",
    ),
    "SAFARI_ZONE_NORTH_FRLG": (
        "ROOKIDEE FOMANTIS SEWADDLE RHYHORN NIDORAN_F KANGASKHAN",
        "PACHIRISU SMOLIV FLETCHLING EXEGGCUTE TAUROS PINSIR",
        "BLITZLE LEDIAN CUFANT HERACROSS PANCHAM DODUO",
        "PHANTUMP HATENNA STANTLER VENONAT NIDORAN_M CHANSEY",
    ),
    "SAFARI_ZONE_WEST": (
        "SKWOVET LILLIPUP KANGASKHAN SCYTHER PINSIR FOMANTIS",
        "MAREEP SMOLIV PACHIRISU EXEGGCUTE TAUROS CHANSEY",
        "YUNGOOS PAWMI DEERLING HERACROSS STANTLER BELLSPROUT",
        "ESPURR STUNKY IMPIDIMP WYNAUT NIDORAN_M DROWZEE",
    ),
    "CERULEAN_CAVE_1F": (
        "ARON SKARMORY KLAWF TYRUNT ONIX GOLEM",
        "STEELIX LUCARIO HAUNTER BISHARP KADABRA CARKOL",
        "LAIRON GRAVELER MACHOKE CARKOL CLEFABLE GURDURR",
        "HELIOLISK DUSCLOPS DRAGONAIR GREAVARD PUPITAR SABLEYE",
    ),
    "CERULEAN_CAVE_2F": (
        "GOLEM GLIGAR TYRUNT CLEFABLE LUXIO SKARMORY",
        "STEELIX LUCARIO GURDURR KLAWF GRAVELER KADABRA",
        "SKARMORY BISHARP TOXTRICITY ELECTRODE SLIGGOO PUPITAR",
        "WEAVILE DUSCLOPS GREAVARD DRAGONAIR TYRUNT HAUNTER",
    ),
    "CERULEAN_CAVE_B1F": (
        "STEELIX GRAVELER MAWILE TYRUNT GOLEM DRAGONAIR",
        "STEELIX TYRUNT KLAWF LUCARIO ELECTRODE KADABRA",
        "SKARMORY GURDURR CLEFABLE BISHARP LAIRON HELIOLISK",
        "PUPITAR DUSCLOPS WEAVILE GREAVARD DRAGONAIR ARBOK",
    ),
    "SEAFOAM_ISLANDS_1F": (
        "SNOM SEEL CUBCHOO SWINUB SHELLDER KRABBY",
        "DEWPIDER STUNFISK SNEASEL EISCUE SLOWPOKE ZUBAT",
        "ARROKUDA SNORUNT CRABRAWLER SPHEAL SEEL ZUBAT",
        "SNEASEL VANILLITE FRILLISH GOLBAT JYNX SNORUNT",
    ),
    "SEAFOAM_ISLANDS_B1F": (
        "CUBCHOO SNOM SWINUB EISCUE SEEL SHELLDER",
        "GLALIE STUNFISK DEWPIDER EISCUE SLOWPOKE SNEASEL",
        "SNORUNT SPHEAL ARROKUDA SEEL JYNX CUBCHOO",
        "SNEASEL VANILLITE FRILLISH GOLBAT SNORUNT DEWGONG",
    ),
    "SEAFOAM_ISLANDS_B2F": (
        "CUBCHOO SNOM SWINUB FRIGIBAX SEEL SHELLDER",
        "STUNFISK DEWPIDER EISCUE SLOWPOKE SNEASEL GLALIE",
        "SNORUNT SPHEAL ARROKUDA JYNX SEEL CUBCHOO",
        "VANILLITE FRILLISH SNEASEL SNORUNT DEWGONG ZUBAT",
    ),
    "SEAFOAM_ISLANDS_B3F": (
        "SNOM CUBCHOO SPHEAL FRIGIBAX SEEL SHELLDER",
        "DEWPIDER STUNFISK EISCUE SLOWPOKE GLALIE SNEASEL",
        "SNORUNT SPHEAL ARROKUDA JYNX SEEL CUBCHOO",
        "VANILLITE FRILLISH SNEASEL SNORUNT DEWGONG ZUBAT",
    ),
    "SEAFOAM_ISLANDS_B4F": (
        "SPHEAL CUBCHOO FRIGIBAX SWINUB SEEL SHELLDER",
        "DEWPIDER STUNFISK EISCUE SLOWPOKE GLALIE SNEASEL",
        "SNORUNT DEWGONG ARROKUDA JYNX SEEL CUBCHOO",
        "VANILLITE FRILLISH SNEASEL SNORUNT DEWGONG ZUBAT",
    ),
}

# map -> (water list, fishing list). Water has 5 slots, fishing 10 (old rod 2, good rod 3, super rod 5).
WATER = {
    "ROUTE12": ("TENTACOOL SLOWPOKE MARILL FINNEON ALOMOMOLA",
                "MAGIKARP TENTACOOL KRABBY STARYU CHINCHOU BARBOACH TYMPOLE CLAMPERL HORSEA ARROKUDA"),
    "ROUTE13": ("TENTACOOL WINGULL KRABBY FINNEON BINACLE",
                "MAGIKARP SHELLDER TENTACOOL HORSEA CORPHISH MANTYKE POLIWAG SKRELP CLAUNCHER FINIZEN"),
    "ROUTE19": ("TENTACOOL WINGULL CHEWTLE MANTYKE PYUKUMUKU",
                "MAGIKARP TENTACOOL SHELLDER STARYU LAPRAS FINIZEN SKRELP WIMPOD FRILLISH ARROKUDA"),
    "ROUTE20": ("TENTACOOL SHELLDER BINACLE CLAUNCHER MAREANIE",
                "MAGIKARP TENTACOOL KRABBY HORSEA STARYU CORSOLA LUVDISC MANTYKE FINIZEN CETODDLE"),
    "ROUTE21_NORTH": ("TENTACOOL WINGULL KRABBY PYUKUMUKU SKRELP",
                      "MAGIKARP TENTACOOL HORSEA SHELLDER STARYU REMORAID CORPHISH MANTYKE ARROKUDA WIMPOD"),
    "ROUTE21_SOUTH": ("TENTACOOL WINGULL KRABBY FINIZEN CHEWTLE",
                      "MAGIKARP SHELLDER KRABBY STARYU CLAMPERL TENTACOOL LUVDISC SKRELP DEWPIDER FRILLISH"),
    "ROUTE23": ("PSYDUCK POLIWAG BUIZEL TYMPOLE BASCULIN",
                "MAGIKARP GOLDEEN PSYDUCK MAREANIE BARBOACH STARYU DEWPIDER CHINCHOU WOOPER ARROKUDA"),
    "CELADON_CITY": ("PSYDUCK POLIWAG MARILL CHEWTLE TYMPOLE",
                     "MAGIKARP GOLDEEN SLOWPOKE POLIWAG BUIZEL BARBOACH CHINCHOU DEWPIDER WOOPER FINNEON"),
    "FUCHSIA_CITY": ("PSYDUCK SLOWPOKE KRABBY FINNEON ALOMOMOLA",
                     "MAGIKARP GOLDEEN KRABBY STARYU CORPHISH BASCULIN POLIWAG HORSEA SKRELP MANTYKE"),
    "CINNABAR_ISLAND": ("TENTACOOL WINGULL SHELLDER BINACLE PYUKUMUKU",
                        "MAGIKARP TENTACOOL KRABBY HORSEA STARYU CLAMPERL LAPRAS MANTYKE ARROKUDA BRUXISH"),
    "SAFARI_ZONE_CENTER": ("PSYDUCK SLOWPOKE WOOPER TYMPOLE CHEWTLE",
                           "MAGIKARP DRATINI GOLDEEN PSYDUCK WOOPER BARBOACH CHEWTLE DEWPIDER BUIZEL FINNEON"),
    "SAFARI_ZONE_EAST": ("PSYDUCK SLOWPOKE CHINCHOU TYMPOLE FINNEON",
                         "MAGIKARP DRATINI GOLDEEN PSYDUCK WOOPER BARBOACH POLIWAG DEWPIDER BUIZEL CHEWTLE"),
    "SAFARI_ZONE_NORTH_FRLG": ("PSYDUCK SLOWPOKE POLIWAG CHEWTLE BASCULIN",
                               "MAGIKARP DRATINI GOLDEEN PSYDUCK MAREANIE BARBOACH SLOWPOKE TYMPOLE BUIZEL WOOPER"),
    "SAFARI_ZONE_WEST": ("PSYDUCK SLOWPOKE MARILL TYMPOLE ALOMOMOLA",
                         "MAGIKARP DRATINI GOLDEEN PSYDUCK WOOPER BARBOACH CHEWTLE DEWPIDER BUIZEL FINNEON"),
    "CERULEAN_CAVE_1F": ("PSYDUCK GOLDUCK SLOWBRO CHINCHOU BASCULIN",
                         "MAGIKARP GOLDEEN POLIWAG WHISCASH SEAKING LANTURN CLAUNCHER SLOWPOKE DEWPIDER BUIZEL"),
    "CERULEAN_CAVE_B1F": ("GOLDUCK POLIWHIRL SLOWBRO LANTURN BASCULIN",
                          "MAGIKARP SEAKING GYARADOS WHISCASH ALOMOMOLA LANTURN FLOATZEL SLOWBRO BARRASKEWDA DRATINI"),
    "SEAFOAM_ISLANDS_B3F": ("SEEL SHELLDER SPHEAL CLAMPERL FINIZEN",
                            "MAGIKARP SEEL SHELLDER KRABBY HORSEA STARYU CLAMPERL FRILLISH ARROKUDA CETODDLE"),
    "SEAFOAM_ISLANDS_B4F": ("DEWGONG SEEL TENTACRUEL WALREIN CETITAN",
                            "MAGIKARP SEEL SHELLDER KRABBY HORSEA STARYU ARROKUDA SPHEAL FRILLISH CETODDLE"),
}
ROCK_SMASH = {
    "CERULEAN_CAVE_1F": "GEODUDE ROGGENROLA ONIX SHUCKLE CARKOL",
    "CERULEAN_CAVE_2F": "GRAVELER BOLDORE ONIX SHUCKLE COALOSSAL",
    "CERULEAN_CAVE_B1F": "GRAVELER BOLDORE STEELIX SHUCKLE COALOSSAL",
}

LAND_WEIGHT_PER_SLOT = LAND_WEIGHTS


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    valid = load_species()
    banned = load_banned()
    with open(JSON_PATH) as f:
        data = json.load(f, object_pairs_hook=OrderedDict)
    encounters = data["wild_encounter_groups"][0]["encounters"]

    def table(map_name, time):
        hits = [e for e in encounters if e["map"] == "MAP_" + map_name and e["base_label"].endswith("_Kanto_" + time)]
        assert len(hits) == 1, f"{map_name} {time}: {len(hits)} tables"
        return hits[0]

    for map_name, lists in LAND.items():
        assert len(lists) == 4
        for time, spec in zip(TIMES, lists):
            ctx = f"{map_name} {time} land"
            sp = parse(spec, 6, ctx, valid, banned, "land")
            set_species(table(map_name, time)["land_mons"], [sp[i] for i in LAND_PATTERN], ctx)

    gen_weight = {g: 0 for g in range(1, 10)}
    for map_name, lists in LAND.items():
        names = {n for spec in lists for n in spec.split()}
        gens = {gen_of(valid[n]) for n in names}
        assert len(gens) >= MIN_MAP_GENS, f"{map_name}: only generations {sorted(gens)} across times"
        for spec in lists:
            for weight, n in zip(LAND_WEIGHT_PER_SLOT, spec.split()):
                gen_weight[gen_of(valid[n])] += weight
    total = sum(gen_weight.values())
    share = {g: round(100 * w / total, 1) for g, w in gen_weight.items()}
    print("land encounter share per generation (%):", share)
    assert min(share.values()) >= MIN_GEN_SHARE, f"a generation is under {MIN_GEN_SHARE}% of land encounters"

    for map_name, (water, fishing) in WATER.items():
        for time in TIMES:
            e = table(map_name, time)
            ctx = f"{map_name} {time}"
            set_species(e["water_mons"], parse(water, 5, ctx + " water", valid, banned, "water"), ctx + " water")
            set_species(e["fishing_mons"], parse(fishing, 10, ctx + " fishing", valid, banned, "fishing"), ctx + " fishing")

    for map_name, spec in ROCK_SMASH.items():
        for time in TIMES:
            ctx = f"{map_name} {time} rock smash"
            set_species(table(map_name, time)["rock_smash_mons"], parse(spec, 5, ctx, valid, banned, "rock smash"), ctx)

    maps = set(LAND) | set(WATER) | set(ROCK_SMASH)
    print(f"maps authored: {len(maps)}  tables touched: {len(maps) * 4}")

    if not args.dry_run:
        with open(JSON_PATH, "w") as f:
            json.dump(data, f, indent=2)
            f.write("\n")


if __name__ == "__main__":
    main()
